### PR TITLE
fix/Entity Restaurant and RestaurantDTO

### LINKED ISSUE #3: Creazione Entity Ristorante

### PR DESCRIPTION
**Pull request by dudinhab**
- Changed type ID(int->long);
- Added ID auto;
- Added name entity;
- Added methods Getter, Setter and Constructor.

### CODE REVIEW

File: src/main/java/com/develhope/Java27_progetto3_team2/entity/Restaurant.java [hunk 1]
```diff
@@ -26,9 +28,11 @@ public class Restaurant {
     @Setter
     @Column(name = "opening_hours")
     public TimeZone openingHours;
+    @Setter
     @OneToOne
     @Column(name = "menu_restaurant_id")
-    private int menuRestaurantID;
+    private long menuRestaurantID;
```
Comment (DonatoAletta) [inline src/main/java/com/develhope/Java27_progetto3_team2/entity/Restaurant.java:34]: change long to Long

File: src/main/java/com/develhope/Java27_progetto3_team2/model/RestaurantDTO.java [hunk 2]
```diff
@@ -1,16 +1,27 @@
...
+import lombok.Setter;
 
 import java.util.TimeZone;
 
+@Getter
+@AllArgsConstructor
+@NoArgsConstructor
 public class RestaurantDTO {
-    private int id;
+    private long id;
```
Comment (DonatoAletta) [inline src/main/java/com/develhope/Java27_progetto3_team2/model/RestaurantDTO.java]: change long to Long

File: src/main/java/com/develhope/Java27_progetto3_team2/entity/Restaurant.java [hunk 3]
```diff
@@ -26,9 +28,11 @@ public class Restaurant {
...
+    @Setter
     @Column(name = "review")
     private double review;
```
Comment (DonatoAletta) [inline src/main/java/com/develhope/Java27_progetto3_team2/entity/Restaurant.java:37]: this review is supposed to be a score or a text review ? since its a double i suppose its a score based review, if so a name like "reviewScore" would be better

File: src/main/java/com/develhope/Java27_progetto3_team2/model/RestaurantDTO.java [hunk 4]
```diff
@@ -1,16 +1,27 @@
...
     private String category;
+    @Setter
     private String address;
+    @Setter
     public TimeZone openingHours;
-    private MenuRestaurant menuRestaurant;
+    @Setter
+    private long menuRestaurant;
+    @Setter
     private double review;
```
Comment (DonatoAletta) [inline src/main/java/com/develhope/Java27_progetto3_team2/model/RestaurantDTO.java:26]: Same as in restaurant.java
